apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: "postgres.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "pscit"

  GOOGLE_CLIENT_ID: "83685543235-7rt7dc891ofvu7kat3m6ikutg06r7af2.apps.googleusercontent.com"

  # Admin Configuration
  ADMIN_EMAIL: "hungcqrt@gmail.com"

  # Server Configuration
  PORT: "8000"
  ENV: "prod"

  # SMTP Configuration for Email Notifications
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "hungcqrt@gmail.com"