apiVersion: ENC[AES256_GCM,data:dmg=,iv:2EQMs6I2kPe76Sy3pOaHJMe6LQkWkhdPdK6pEQZBOuM=,tag:xhxvHGLlOKJb1cKxoTaGxw==,type:str]
kind: ENC[AES256_GCM,data:0dE+zoRx,iv:i3KkhEUcw6N0azjVw0FkFbXMPf1d/j0/3xgY5aEeRGs=,tag:qWixrr9iPdrQMzoL9i64iw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:90jINiYVoK7w9zuPAZAV,iv:Tg6Wu14gzHyUZxunNwCs0FlLJRxkB7EcPe3ZfhNA8VI=,tag:BRTbZzxjlJ9MvljnLi0J9Q==,type:str]
type: ENC[AES256_GCM,data:TYOC4bD8,iv:csb0bzhIz3rFipFVA3mtrD+vUZB7+ACAG2+keU0x95Q=,tag:yks5b2lVidTxj3IsPPDZcA==,type:str]
data:
    #ENC[AES256_GCM,data:T2ds6a9CNVCoYGR1Cz2EMFFkZvxxtd5QTXYGcA==,iv:wNOJ+fTBItqzLIJKddb1xKgzo+OzdJTyhfKg+kNrkq4=,tag:dKYfhviTHoh1pcdVB1zBMg==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:Wllyuk4a3VHZY2XXfafj3DkZ5Du63+hJCM76+A==,iv:+dOPr+v511Jys4BYO6dyCNEsx+U5gNZa/3tGWCldxuE=,tag:sFYeOfxaknr0S9F4Zx96og==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:cOALQVWKN4B2jE8CVP9f4stGoNWKwH82g9ZPtmsorM2LOcNtP/Y+MXHN9hw=,iv:ljIMvJ/4hoeUDmOAIsFCvl1YBgyB84SkkbhQFK3ChJw=,tag:tLy3HdnRKPCKF5yTJ20bTQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:TvUO5ME7CjV6QwruB05gLBwk5sXu4TxLAujJ2p4Xy23XT3t0,iv:55dBz9UMHqQkX0nbqs4laJWclLlTz/Ib9La6+FZRsUQ=,tag:UYkk47vya+jmj7qE6j0jTA==,type:str]
sops:
    age:
        - recipient: age1alrmt6qp308t0ww7ud0pynxwk636vz7r9u6qr5cehsu7747acdts8aulky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyb0RvZzRiTGpwNk5jRy9B
            bHBML0ZPRWE4L2t6N0FhR09kSGc2a25rRmxNCnFrZmVWQ2FueGtobzVXcFNRa1Bl
            dXNIL2tSdm1XKzJIemNNZkxnbkJaWFkKLS0tIE4wUUYzWm1ZRjIvbjF0MC91N2NY
            djdpckN4aE5ncEVBQngyVEEySVAwbjgKG77p2pAlghY7PqG3nhkH4dYukojViJnt
            sSq5qiLF1wGkPP0YxHHEAl4l/8Z5ND+raTZDPkM2d05LuL2pI/3JYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T16:03:55Z"
    mac: ENC[AES256_GCM,data:4kNdaNZmnmLWBgro+oPW3MZSW2GkoV6Csg5CoKApqacTznyZWwTVR2cu8cyTAujrwUoTVUH1hAyRRc17HIAY8bZL7dPHJbl2ixUjKotvA+EME3CAoddu7UXEhIR39UEBbvK47+/7pMckI1tIjhVIla12BNpw1opPraWc2Mc6R9A=,iv:PVJyaWU5bCroLIPrXxcKnl/jI3J5CQ19rMdZN6bVRBc=,tag:qicoCLZQ0R7oUydUURSEvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
