apiVersion: ENC[AES256_GCM,data:VCc=,iv:fElXbfnUA1gXZxXmamvhRej5vIFMx9FuwoUS+J6IkJA=,tag:vez4BR8ZZ/JMcM0JqWlIeA==,type:str]
kind: ENC[AES256_GCM,data:8K3b4kQp,iv:1XxUbFxNtO2QzEOBkZXBmZ05nhewrTpnE2ZfVFBAScE=,tag:wtluYY8rXMSxtQ+fCBm1Qg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nPIbO1ZOtqxTGd7ZWOAC,iv:emS6xGWTifuUszkbWhWDpNnd+u1M+DoScBfPTt+V6Zg=,tag:rNY6KV27RZnpwvDLKBxffw==,type:str]
type: ENC[AES256_GCM,data:SJTykx8M,iv:Pr3R2zj5RWoJwmNri+hf9ugIYuBCSOksUCH0TPNe8IA=,tag:O3CLxYvr58nl9UCiVI8OBw==,type:str]
data:
    #ENC[AES256_GCM,data:xApUNoRyw/W5/tWTe7L3RlFKogI7FOXI7yPlhQ==,iv:+ch78vWJic2HYad1N+ti2Frslz/T8p++9WOKwBIt9Lo=,tag:gQbqTiBUO2VfYsfR8IgskA==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:uGM7JHbmSQCWJrTEMYc4WsWUlhJnqKTRNhwUvw==,iv:lcpDsa+KVh4jbnAsqX35ZXEenobp2eNJnTQnPhyNc2M=,tag:68LthqIpvAGf/QAKUIFKVw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:dWMei/pQ1f1VfXdlWC7ihpUyOjoOBuFQbyOm3ekgSNIdNRnyz6o3UMmITwA=,iv:VCnCen1xdwMJAIRzxsSniNoyG6OrZpEBnwD5B9GkQTw=,tag:JIAGvnVV4HYhTEvsMvC8vw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:E67iVU2UXo36m7tLewTYk38kEg==,iv:hEEqYf4IHWK3VKNAFNCieN9MYD1pnVospBgVNEkRD40=,tag:0eys8bEaNADE+KfIWFxgEQ==,type:str]
sops:
    age:
        - recipient: age1alrmt6qp308t0ww7ud0pynxwk636vz7r9u6qr5cehsu7747acdts8aulky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVWU3bi8zbmViajl5NDVk
            N2lVWDE0SnhIejM3czV3RktXWFNOdlFwdjBZCm14ZzFoNjFVRUszRmVPWksxOFA3
            UXdTdEcyQkx1MUlVYmZMYlZlUXBoQXMKLS0tIHRMYWRQNE0yQ2tWclV0QVZLd0ZL
            UjZoSlZhb0NDUFdIVU9Tb3hWQ0ZySEkK8VV+2wcLN3gtZBpd/Tuwb1vz3Iq+CqE3
            OCirqkbtZmXHnw5U8xWXZqMT2bn0ytRbEQJuZMcB2YBVCkwG7ReBQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T16:45:20Z"
    mac: ENC[AES256_GCM,data:FVIUvmj+/7DJhlNTvgfaLRCqhmDjr7HHxZ+jdjej5IjCql8urqhUh2yf6AekheHWTBM4Bnhm6sb+eyZO9/UTjU//NRXae4HmsVTdXhfLBsQ+RpOm4BPew9Ob5S8vwNlQp0YpJjId2qrxfL4sAEMVvOfHMJSS5FZLFIEB2F+2imM=,iv:EBeQ0etSnFik42mEnRPIJ5fzRvhgGGdd21t4RWSoeu0=,tag:CTHaoqoMaD9foEsrWbEP3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
