apiVersion: ENC[AES256_GCM,data:jkk=,iv:1iAKNsUVaZPZLe+x8j5JRIzjtCuXZDlconVDIDFTGu4=,tag:56yGcULqNTKSJf+dFIIa6Q==,type:str]
kind: ENC[AES256_GCM,data:CYsfNT3M,iv:HFTVSKdnnxoqAtyLJpe8DGAQ4LhWd9d3bk7xp+qz9Vo=,tag:ua8wplg4NEKsrcmJlXSLUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+tXA1Jqpe9KKjTnpyr2K,iv:d6SCovy2DWn+27YhlypUEtTqUwrCC3ORlG4XMoc3ItQ=,tag:BYQFBpnKz16DYkS41u697w==,type:str]
type: ENC[AES256_GCM,data:KDmm78i+,iv:dnRoTJlC3TWrqYMBE8ucIBG5DI8KzJ1vg/8ZstgugCg=,tag:UgWpgvSZUcfCK00z1XHuRQ==,type:str]
data:
    #ENC[AES256_GCM,data:u3eVYgU1qco0gw9dekAY3HqP0Nn1tamrDfw6yw==,iv:VQm00VUFm7xDk4pYw54RrjPBjSqJVnzMjpUUcuUqzZQ=,tag:2/qCmKban1MK6AZko2ttiA==,type:comment]
    #ENC[AES256_GCM,data:uQUAwtY+lXSmWCJ3PyZR82P9LVpxSqnK1oNmuzHDVGeYJBe8J1kshcw=,iv:xpOt1FX5vNaRtPggyg3jzl9/q+V7EZsVC6BJWjxBfjI=,tag:wa5kXUzg1GuA9j3nK7oMGQ==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:wwBLDwVFtP58vw1y7Lpg6HlSMljy23y8QDbh6w==,iv:BYNxxdEndSVjqy4RycreLrOyShQJhCfqjKwDiISzPnU=,tag:ex8srLn+muFAqGKylgmW8w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:MsQUwpHwPu4meq7idgl0cE/4o0nHY73VYiqJTyF9k277L1YtdK5FsOhVChg=,iv:LTqsPs0SNFJioy2Bg9feLm0ejlB64CEbg4CoPgRFs/g=,tag:XYUu5xF08zXsPfrdEmQCOQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:zo7tZr+r11J4M5xFJg/JyQiUErvpzBfjuQSCJg==,iv:YJwNlPqD8LkK4TTH4oqEpmoL2+PXBrXSV39qK+2qR/M=,tag:2AcYZDHHRWHecYQMYg2h+w==,type:str]
    DATA_SOURCE_NAME: ENC[AES256_GCM,data:rZ86owyTmcwobKskXRVbYQnh23N95VsyUy/KJMCL6S+Xi2Dbc87QyuaQh7xemnrN2TjEIWw5muFFPmprIpEHi+7XwNoCbsBJPl/Xxbsj7DugSLMC02fdMG3Jn/ElhKS7LduxWR8B4NlFBI2g4LahZfE0q2v+nYoM9zjL1kOmQTFRwhctcTZ+xsPe/po=,iv:xO3kA36rh8b0+2Flc4HcempMgsPNwJxGeMNB9ffYiFQ=,tag:OdEMe9cFa2Vsm4BcQpvPUQ==,type:str]
sops:
    age:
        - recipient: age1alrmt6qp308t0ww7ud0pynxwk636vz7r9u6qr5cehsu7747acdts8aulky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK0NxRzVvYmFNRGQ3aG9U
            aS9IWWdNZ29sYW1XaVQ5M2lxQ0tHbk5hTVNNCjhEWWM2ZGFodEdxMnhvRnhISSts
            TGt6V0tqdTNSS1dURCttbkZreXUvbzgKLS0tIEUxeGtOdGgrSk52Q21rVk9TUCtI
            b2x0MFZSYjBZQ2Q4SHlwbWlGVlcvU1EKLuqfbVCXkuvwszbwFT75d0wNOB8ycYhq
            anGrLo//35O3EBwGaEHO609G187W8MRPu9hMe7as59KyZdtbIZ1uUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T03:03:50Z"
    mac: ENC[AES256_GCM,data:Ibw+uZWVnn3u9ch9bZBDEhlJgkiY4HZTi4lQHCe+bvynpynC7GiGb3+t4ue0u/2d3zMyiQJBgfIyNGwA3w3GZky9QVLvpO4VXPVW5lTUo8sZakT9XFrzWhKwAVA4v2+T1QHDtaMfhcrgUl2LJva1Gkx0S0z0vFmcYqxqXcNYemE=,iv:sSb4DJA4/0a5PUoLHIoRlTHQY3M/Pl9Y/m0FMxlvwDE=,tag:E7fa3Uy4mXJO0D8HXOLNcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
