apiVersion: v1
kind: Service
metadata:
  name: author-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: author-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service-deployment
spec:
  selector:
    matchLabels:
      app: author-service
  replicas: 2
  template:
    metadata:
      labels:
        app: author-service
        version: v1
    spec:
      containers:
        - name: author-service
          image: hungcq/author-service:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD