apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: book-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
spec:
  selector:
    matchLabels:
      app: book-service
  replicas: 1
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: book-service
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: AUTHOR_SERVICE
              value: author-service:80
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: log
              mountPath: /var/log
        - name: fluentd
          image: my-fluentd
          imagePullPolicy: Never
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
            - name: log
              mountPath: /var/log
      volumes:
        - name: log
          emptyDir: { }
        - name: fluentd-config
          configMap:
            name: fluentd-config