name: Build Backend Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/*'
      - 'backend/*/**'     # include all subdirs *except* scripts
      - '!backend/scripts/**'
      - 'k8s/**'
      - '.github/workflows/build.yaml'
      - '.github/workflows/deploy.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Generate version
        id: version
        run: echo "VERSION=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and tag image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pscit-backend:${{ steps.version.outputs.VERSION }} ./backend
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/pscit-backend:${{ steps.version.outputs.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/pscit-backend:latest

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pscit-backend:${{ steps.version.outputs.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pscit-backend:latest
