name: Deploy to Kubernetes

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'k8s/**'
      - '.github/workflows/deploy.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo (YAMLs)
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image
        run: docker build -t pscit/backend:latest ./backend

      - name: Tag image
        run: docker tag pscit/backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/pscit-backend:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pscit-backend:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          # Verify connection
          kubectl cluster-info

      - name: Install SOPS
        run: |
          wget -O sops https://github.com/mozilla/sops/releases/download/v3.8.0/sops-v3.8.0.linux
          chmod +x sops
          sudo mv sops /usr/local/bin/

      - name: Decrypt secrets
        run: |
          echo "${{ secrets.SOPS_AGE_KEY }}" > age.key
          chmod 600 age.key
          SOPS_AGE_KEY_FILE=age.key sops -d k8s/secret.enc.yaml > k8s/secret.yaml
          rm age.key

      - name: Apply manifests
        run: |
          # Verify cluster connection before applying
          kubectl cluster-info
          # Apply manifests with validation disabled
          kubectl apply -f k8s/configmap.yaml --validate=false
          kubectl apply -f k8s/secret.yaml --validate=false
          kubectl apply -f k8s/backend-deployment.yaml --validate=false
          kubectl apply -f k8s/backend-ingress.yaml --validate=false