name: Deploy to Kubernetes

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo (YAMLs)
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image
        run: docker build -t pscit/backend:latest ./backend

      - name: Tag image
        run: docker tag pscit/backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/pscit-backend:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pscit-backend:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Install SOPS
        run: |
          wget -O sops https://github.com/getsops/sops/releases/download/v3.10.2/sops-v3.10.2.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/

      - name: Decrypt secrets
        run: |
          echo "${{ secrets.SOPS_AGE_KEY }}" > age.key
          chmod 600 age.key
          SOPS_AGE_KEY_FILE=age.key sops -d k8s/secret.enc.yaml > k8s/secret.yaml
          rm age.key

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-ingress.yaml